version: "3.8"

services:
  dbmysql:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=  # Replace with the actual MySQL root password
      - MYSQL_DATABASE=db  # Set database name to 'db'
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  TpFoyer:
    depends_on:
      - dbmysql
    image: mrad221/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - "8085:8089"  # Map host port 8085 to container port 8089 (Spring Boot app)
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://dbmysql:3306/db?useSSL=false&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",  # Replace with the actual MySQL root password
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.port": "8089",
        "server.servlet.context-path": "/tpfoyer"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
